// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Tyruswoo_CameraControl","status":true,"description":"MZ v1.1.2 Provides greater control of the camera!","parameters":{}}
];
